version: '2'
services:
  db:
    image: postgres:10.3-alpine
    build: ./
    ports:
    - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_PASSWORD}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
       - ./var/lib/postgresql/data:/var/lib/postgresql/data
